# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_M2_c <- function(nSize, nSpecies, N, scLinf, ration, wgt, suitability, phiMin, otherFood) {
    .Call('_LeMANS_calc_M2_c', PACKAGE = 'LeMANS', nSize, nSpecies, N, scLinf, ration, wgt, suitability, phiMin, otherFood)
}

